version: "3.8"

services:
  # ---------------------------------------------------------
  # 1. The Local DNS Server (Target)
  # ---------------------------------------------------------
  dns-server:
    image: ubuntu:22.04
    container_name: local-dns-server
    tty: true
    cap_add:
      - NET_ADMIN
    networks:
      dns-net:
        ipv4_address: 10.9.0.53
    # Automatically updates apt, installs dnsmasq + dnsutils, and starts dnsmasq in the foreground
    command: >
      bash -c "DEBIAN_FRONTEND=noninteractive apt-get update && 
      DEBIAN_FRONTEND=noninteractive apt-get install -y dnsmasq dnsutils tcpdump net-tools && 
      echo 'user=root' > /etc/dnsmasq.conf &&
      echo 'no-resolv' >> /etc/dnsmasq.conf &&
      echo 'server=10.9.0.254' >> /etc/dnsmasq.conf &&
      echo 'log-queries' >> /etc/dnsmasq.conf &&
      dnsmasq -k --no-resolv --server=/#/10.9.0.254"

  # ---------------------------------------------------------
  # 2. The Victim Node (Client)
  # ---------------------------------------------------------
  victim:
    image: ubuntu:22.04
    container_name: victim-node
    tty: true
    networks:
      dns-net:
        ipv4_address: 10.9.0.5
    # Automatically installs utilities and points the resolver to our target DNS container
    command: >
      bash -c "DEBIAN_FRONTEND=noninteractive apt-get update && 
      DEBIAN_FRONTEND=noninteractive apt-get install -y dnsutils iputils-ping && 
      echo 'nameserver 10.9.0.53' > /etc/resolv.conf && 
      tail -f /dev/null"

  # ---------------------------------------------------------
  # 3. The Attacker Node
  # If using wsl for the containers you need to add a secondary ip address 
  # for the upstream internet gateway. This is so the attack container is able "sniff" 
  # the traffic, and correctly stage the cache poisoning attack. 
  # Command I used inside the attack container: ip addr add 10.9.0.254/24 dev eth0
  # ---------------------------------------------------------
  attacker:
    image: ubuntu:22.04
    container_name: attacker-node
    tty: true
    cap_add:
      - NET_ADMIN  # Allows Scapy to interact with raw network sockets
    networks:
      dns-net:
        ipv4_address: 10.9.0.100
    volumes:
      - .:/app      #for the attack script.
    command: >
      bash -c "DEBIAN_FRONTEND=noninteractive apt-get update && 
      DEBIAN_FRONTEND=noninteractive apt-get install -y python3 python3-pip python3-scapy tcpdump nano net-tools && 
      tail -f /dev/null"

networks:
  dns-net:
    name: dns-net
    driver: bridge
    ipam:
      config:
        - subnet: 10.9.0.0/24
          gateway: 10.9.0.1